#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: https://meta.inn.eu/revault

annotationTypes:
  deny:
    properties:
      if: string
  authorize:
    properties:
      if: string

/test:
  (authorize):
    if: uri.userId = context.authUser.id
  (deny):
    if: !context.isAuthorized
