#%RAML 1.0
title: Facade API
version: v1
mediaType: application/json
baseUri: https://meta.inn.eu/revault
types:
  User:
    type: object
    properties:
      fullName: string
      userName: string
      password:
        (deny):
        type: string

annotationTypes:
  x-client-ip:
  x-client-language:
  deny:
  rewrite:

/resource/reliable-feed:

/resource/unreliable-feed:

/original-resource/{serviceId}:
  (rewrite):
    uri: /rewritten-resource/{serviceId}

/resource:

# Event Rewrite Test Resources
/events:
  (rewrite):
    uri: /rewritten-events/root

/events/{path}:
  feed:put:
    (rewrite):
      uri: /rewritten-events/root/{path}

/rewritten-events/{path:*}:

/users/{userId}:
  get:
    responses:
      200:
        body:
          type: User
  feed:put:
    body:
      application/json:
        type: User