#%RAML 1.0
title: Facade API
version: v1
traits:
  secured:
  paged:
  rateLimited:
  private:
/users:
  is: [ secured ]
  get:
    is: [ paged, rateLimited ]
/status:
  get:
    is: [ rateLimited ]
  /test-service:
    get:
      is: [ paged ]
/private:
  is: [ private ]